vim.g['test#strategy'] = 'vimux'
vim.g['test#echo_command'] = 0
vim.keymap.set('n', '<leader>tc', ':TestNearest<CR>', { silent = true })
vim.keymap.set('n', '<leader>tf', ':TestFile<CR>', { silent = true })
vim.keymap.set('n', '<leader>ta', ':TestSuite<CR>', { silent = true })
vim.keymap.set('n', '<leader>tl', ':TestLast<CR>', { silent = true })
vim.keymap.set('n', '<leader>tg', ':TestVisit<CR>', { silent = true })
vim.keymap.set('n', '<leader>tcw', ':TestNearest --watch<CR>', { silent = true })
vim.keymap.set('n', '<leader>tfw', ':TestFile --watch<CR>', { silent = true })
vim.keymap.set('n', '<leader>taw', ':TestSuite --watch<CR>', { silent = true })
vim.keymap.set('n', '<leader>tlw', ':TestLast --watch<CR>', { silent = true })
vim.keymap.set('n', '<leader>tgw', ':TestVisit --watch<CR>', { silent = true })
